// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB99AkO1wMWLv5yC_Yr62z8qgYEugcSWPY',
    appId: '1:115957456766:web:f902eece05d5e231fe9d2f',
    messagingSenderId: '115957456766',
    projectId: 'flutterchatapp-62dcc',
    authDomain: 'flutterchatapp-62dcc.firebaseapp.com',
    storageBucket: 'flutterchatapp-62dcc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvwynIMjZIcE5eUkug1giICphG_rikr6g',
    appId: '1:115957456766:android:d2094d4bb425f4c4fe9d2f',
    messagingSenderId: '115957456766',
    projectId: 'flutterchatapp-62dcc',
    storageBucket: 'flutterchatapp-62dcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtDyFdBiQyrsrFHqWLv8YWPrbfLhHCQN0',
    appId: '1:115957456766:ios:c64e28564f1465fcfe9d2f',
    messagingSenderId: '115957456766',
    projectId: 'flutterchatapp-62dcc',
    storageBucket: 'flutterchatapp-62dcc.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtDyFdBiQyrsrFHqWLv8YWPrbfLhHCQN0',
    appId: '1:115957456766:ios:e7199273da41296afe9d2f',
    messagingSenderId: '115957456766',
    projectId: 'flutterchatapp-62dcc',
    storageBucket: 'flutterchatapp-62dcc.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
